/**
 * versions.ts — exercise versions/lifecycle and draft snapshot types.
 *
 * Routes: GET /api/exercises/:id/versions[/:versionID], GET/PUT :id/draft,
 *   POST :id/publish, POST :id/checkpoints, POST :id/versions/:versionID/restore.
 *
 * DTO types transcribe the backend's exercise.saveDraftRequest/versionResponse 1:1
 * (PascalCase, omitempty fields are optional). Normalized* is the read model for the
 * form: every optional field is filled with a concrete default ("", [], null).
 *
 * Key contracts:
 *  - variant.ID is empty for a new variant (backend generates a UUIDv7); EXISTING IDs
 *    must be sent back — the secrets key is (variant ID, device Name, env Name);
 *  - device.ID for NEW devices is generated by the client (crypto.randomUUID()), otherwise
 *    Connections/LinkedDeviceID couldn't reference the device before it's saved;
 *  - Flag: [] → random on deployment; 1 value → fixed;
 *    several → chosen on deployment;
 *  - EnvVar.Value is write-only: empty in responses, HasValue=true if a value
 *    is stored; an empty Value on save means "keep the stored one";
 *  - VisualRender is opaque backend JSON; the editor preserves its canvas layout.
 */
import { apiGet, apiPost, apiPut, apiKeepalive } from "@/api/client"

const BASE = "/api/exercises"

export type VersionStatus = "draft" | "published" | "unpublished" | "checkpoint"
export type Difficulty = "trivial" | "easy" | "medium" | "hard" | "insane"
export type DeviceType = "container" | "unmanaged-switch" | "hub"
export type IPType = "static" | "dhcp" | "dhcp-preset" | "none"
export type SecurityPreset = "" | "basic" | "service" | "net" | "debug"
export type EndpointKind = "device" | "vpn" | "internet"
export type Protocol = "http" | "https"
export type PlaceholderKind = "vpn.subnet" | "internet.subnet" | "ip" | "external.link"

/** Lexical JSON (json.RawMessage on the backend) — opaque object. */
export type LexicalDoc = Record<string, unknown>

export type AttachmentDTO = { FileID: string; Name: string }

export type PlaceholderDTO = {
  Key?: string // stable reference for inline description tokens
  Kind: PlaceholderKind
  IPReference?: string // "vpn" | "internet" | "static" (only when Kind === "ip")
  Octets1to3?: string // only when IPReference === "static"
  LastOctet?: number // 0..255
  ShowMask?: boolean
  DeviceName?: string // only when Kind === "external.link"
}

export type EnvVarDTO = {
  Name: string
  Value?: string
  Secret: boolean
  HasValue?: boolean // response-only
}

export type ExternalDTO = { Port: number; Protocol: Protocol }

export type NetworkIPRefDTO = { Network: "vpn" | "internet"; Host: number }
export type NetworkSubnetRefDTO = { Network: "vpn" | "internet" }

export type IPConfigDTO = {
  Type: IPType
  Addresses?: string[] // CIDR, static only
  AddressRef?: NetworkIPRefDTO | null
  Gateway?: string // static only
  GatewayRef?: NetworkIPRefDTO | null
  Routes?: RouteDTO[] // static only
}

export type RouteDTO = {
  Dst?: string
  DstRef?: NetworkSubnetRefDTO | null
  Via?: string
  ViaRef?: NetworkIPRefDTO | null
}

export type NormalizedRoute = {
  Dst: string
  DstRef?: NetworkSubnetRefDTO | null
  Via: string
  ViaRef?: NetworkIPRefDTO | null
}
export type DeviceResourcesDTO = { CPURequest?: string; MemoryRequest?: string; CPULimit?: string; MemoryLimit?: string }
export type NormalizedDeviceResources = Required<DeviceResourcesDTO>

export type InterfaceDTO = { Name: string; MAC?: string; IP: IPConfigDTO }

export type DeviceDTO = {
  ID?: string
  Name: string // DNS label for containers; display name for switches/hubs
  Type: DeviceType
  SecurityPreset?: Exclude<SecurityPreset, "">
  Image?: string
  Resources?: DeviceResourcesDTO
  Interfaces?: InterfaceDTO[]
  EnvVars?: EnvVarDTO[]
  External?: ExternalDTO
}

export type EndpointDTO = { Kind: EndpointKind; DeviceID?: string; Interface?: string }
export type ConnectionDTO = { Endpoints: EndpointDTO[] } // exactly 2
export type DHCPRangeDTO = { Start: number; End: number }
export type NetworkDTO = { Enabled: boolean; DHCP: boolean; DHCPRanges?: DHCPRangeDTO[]; DNS?: string }

export type TopologyDTO = {
  VPN: NetworkDTO
  Internet: NetworkDTO
  Devices?: DeviceDTO[]
  Connections?: ConnectionDTO[]
  VisualRender?: Record<string, unknown>
}

/** Hint: ID and Cost match position-wise across variants; Text is per variant. */
export type HintDTO = { ID?: string; Text: string; Cost: number }
export type NormalizedHint = { ID: string; Text: string; Cost: number }

export type TaskDTO = {
  ID?: string
  Name: string
  Description?: LexicalDoc | null
  Difficulty: Difficulty
  Flag?: string[]
  LinkedDeviceID?: string
  DeviceFlagVar?: string
  Attachments?: AttachmentDTO[]
  Placeholders?: PlaceholderDTO[]
  Hints?: HintDTO[]
}

export type VariantDTO = {
  ID?: string
  Index: number // decorative number; identity = ID
  Note?: string
  Tasks: TaskDTO[]
  Topology: TopologyDTO
}

export type SaveDraftInput = {
  AdminNote: string
  Variants: VariantDTO[]
}

export type VersionListItem = {
  ID: string
  Status: VersionStatus
  AdminNote: string
  Label: string // snapshot caption; "" when none
  VariantCount: number
  CreatedAt: string
  CreatedBy: string | null
  PublishedAt: string | null
}

// ── Normalized read model (every optional field filled) ────────────────────────

export type NormalizedTask = {
  ID: string
  Name: string
  Description: LexicalDoc | null
  Difficulty: Difficulty
  Flag: string[]
  LinkedDeviceID: string
  DeviceFlagVar: string
  Attachments: AttachmentDTO[]
  Placeholders: PlaceholderDTO[]
  Hints: NormalizedHint[]
}

export type NormalizedEnvVar = { Name: string; Value: string; Secret: boolean; HasValue: boolean }

export type NormalizedInterface = {
  Name: string
  MAC: string
  IP: {
    Type: IPType
    Addresses: string[]
    AddressRef?: NetworkIPRefDTO | null
    Gateway: string
    GatewayRef?: NetworkIPRefDTO | null
    Routes: NormalizedRoute[]
  }
}

export type NormalizedDevice = {
  ID: string
  Name: string
  Type: DeviceType
  SecurityPreset: SecurityPreset
  Image: string
  Resources: NormalizedDeviceResources
  Interfaces: NormalizedInterface[]
  EnvVars: NormalizedEnvVar[]
  External: ExternalDTO | null
}

export type NormalizedEndpoint = { Kind: EndpointKind; DeviceID: string; Interface: string }
export type NormalizedConnection = { Endpoints: NormalizedEndpoint[] }

export type NormalizedTopology = {
  VPN: NetworkDTO
  Internet: NetworkDTO
  Devices: NormalizedDevice[]
  Connections: NormalizedConnection[]
  VisualRender: Record<string, unknown> | null
}

export type NormalizedVariant = {
  ID: string
  Index: number
  Note: string
  Tasks: NormalizedTask[]
  Topology: NormalizedTopology
}

export type Version = {
  ID: string
  ExerciseID: string
  Status: VersionStatus
  AdminNote: string
  Label: string // snapshot caption; "" when none
  Variants: NormalizedVariant[]
  CreatedAt: string
  CreatedBy: string | null
  PublishedAt: string | null
}

// ── Normalize ──────────────────────────────────────────────────────────────────

function normalizeTask(raw: TaskDTO): NormalizedTask {
  return {
    ID: raw.ID ?? "",
    Name: raw.Name,
    Description: raw.Description ?? null,
    Difficulty: raw.Difficulty,
    Flag: raw.Flag ?? [],
    LinkedDeviceID: raw.LinkedDeviceID ?? "",
    DeviceFlagVar: raw.DeviceFlagVar ?? "",
    Attachments: raw.Attachments ?? [],
    Placeholders: raw.Placeholders ?? [],
    Hints: (raw.Hints ?? []).map((hint) => ({ ID: hint.ID ?? "", Text: hint.Text ?? "", Cost: hint.Cost ?? 0 })),
  }
}

function normalizeInterface(raw: InterfaceDTO): NormalizedInterface {
  return {
    Name: raw.Name,
    MAC: raw.MAC ?? "",
    IP: {
      Type: raw.IP?.Type ?? "none",
      Addresses: raw.IP?.Addresses ?? [],
      AddressRef: raw.IP?.AddressRef ?? null,
      Gateway: raw.IP?.Gateway ?? "",
      GatewayRef: raw.IP?.GatewayRef ?? null,
      Routes: (raw.IP?.Routes ?? []).map((route) => ({
        Dst: route.Dst ?? "", DstRef: route.DstRef ?? null,
        Via: route.Via ?? "", ViaRef: route.ViaRef ?? null,
      })),
    },
  }
}

function normalizeDevice(raw: DeviceDTO): NormalizedDevice {
  return {
    ID: raw.ID ?? "",
    Name: raw.Name,
    Type: raw.Type,
    SecurityPreset: raw.SecurityPreset ?? "",
    Image: raw.Image ?? "",
    Resources: {
      CPURequest: raw.Resources?.CPURequest ?? "",
      MemoryRequest: raw.Resources?.MemoryRequest ?? "",
      CPULimit: raw.Resources?.CPULimit ?? "",
      MemoryLimit: raw.Resources?.MemoryLimit ?? "",
    },
    Interfaces: (raw.Interfaces ?? []).map(normalizeInterface),
    EnvVars: (raw.EnvVars ?? []).map((ev) => ({
      Name: ev.Name,
      Value: ev.Value ?? "",
      Secret: ev.Secret,
      HasValue: ev.HasValue ?? false,
    })),
    External: raw.External ?? null,
  }
}

function normalizeTopology(raw: TopologyDTO | null | undefined): NormalizedTopology {
  return {
    VPN: raw?.VPN ?? { Enabled: false, DHCP: false },
    Internet: raw?.Internet ?? { Enabled: false, DHCP: false },
    Devices: (raw?.Devices ?? []).map(normalizeDevice),
    Connections: (raw?.Connections ?? []).map((c) => ({
      Endpoints: (c.Endpoints ?? []).map((ep) => ({
        Kind: ep.Kind,
        DeviceID: ep.DeviceID ?? "",
        Interface: ep.Interface ?? "",
      })),
    })),
    VisualRender: raw?.VisualRender ?? null,
  }
}

export function normalizeVariant(raw: VariantDTO): NormalizedVariant {
  return {
    ID: raw.ID ?? "",
    Index: raw.Index,
    Note: raw.Note ?? "",
    Tasks: (raw.Tasks ?? []).map(normalizeTask),
    Topology: normalizeTopology(raw.Topology),
  }
}

type RawVersion = Omit<Version, "Variants" | "Label"> & { Variants: VariantDTO[] | null; Label?: string }

function normalizeVersion(raw: RawVersion): Version {
  return { ...raw, Label: raw.Label ?? "", Variants: (raw.Variants ?? []).map(normalizeVariant) }
}

// ── API ────────────────────────────────────────────────────────────────────────

/** GET /api/exercises/:id/versions */
export async function listVersions(exerciseId: string): Promise<VersionListItem[]> {
  const raw = await apiGet<(Omit<VersionListItem, "Label"> & { Label?: string })[] | null>(`${BASE}/${exerciseId}/versions`)
  return (raw ?? []).map((item) => ({ ...item, Label: item.Label ?? "" }))
}

/** GET /api/exercises/:id/versions/:versionID */
export async function getVersion(exerciseId: string, versionId: string): Promise<Version> {
  const raw = await apiGet<RawVersion>(`${BASE}/${exerciseId}/versions/${versionId}`)
  return normalizeVersion(raw)
}

/** PUT /api/exercises/:id/draft — full snapshot */
export async function saveDraft(exerciseId: string, input: SaveDraftInput): Promise<Version> {
  const raw = await apiPut<RawVersion>(`${BASE}/${exerciseId}/draft`, input)
  return normalizeVersion(raw)
}

/** POST /api/exercises/:id/publish */
export async function publishDraft(exerciseId: string): Promise<Version> {
  const raw = await apiPost<RawVersion>(`${BASE}/${exerciseId}/publish`, {})
  return normalizeVersion(raw)
}

/** ID of the empty working copy (no draft row, nothing published). Never used in version routes. */
export const EMPTY_VERSION_ID = "00000000-0000-0000-0000-000000000000"

export function isStoredVersionId(id: string): boolean {
  return id !== "" && id !== EMPTY_VERSION_ID
}

/** GET /api/exercises/:id/draft — the working copy (published content when no draft row exists). */
export async function getDraft(exerciseId: string): Promise<Version> {
  return normalizeVersion(await apiGet<RawVersion>(`${BASE}/${exerciseId}/draft`))
}

/** PUT /api/exercises/:id/draft with keepalive — only for pagehide. */
export function saveDraftKeepalive(exerciseId: string, input: SaveDraftInput): boolean {
  return apiKeepalive("PUT", `${BASE}/${exerciseId}/draft`, input)
}

/** POST /api/exercises/:id/checkpoints — snapshot of the working copy with an optional caption (≤ 500). */
export async function createCheckpoint(exerciseId: string, note = ""): Promise<Version> {
  const trimmed = note.trim()
  const raw = await apiPost<RawVersion>(`${BASE}/${exerciseId}/checkpoints`, trimmed ? { Note: trimmed } : {})
  return normalizeVersion(raw)
}

/** POST /api/exercises/:id/versions/:versionID/restore — preserves the current draft. */
export async function restoreVersion(exerciseId: string, versionId: string): Promise<Version> {
  const raw = await apiPost<RawVersion>(`${BASE}/${exerciseId}/versions/${versionId}/restore`, {})
  return normalizeVersion(raw)
}
